# Generated by Django 3.1 on 2020-08-27 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmbitoCultural',
            fields=[
                ('id_ambito', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ambito', models.CharField(max_length=70)),
            ],
            options={
                'verbose_name': 'Ambito Cultural',
                'verbose_name_plural': 'Ambitos Culturales',
                'db_table': 'ambito_cultural',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'categoria',
                'ordering': ['nombre_categoria'],
            },
        ),
        migrations.CreateModel(
            name='Parroquia',
            fields=[
                ('id_parroquia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_parroquia', models.CharField(max_length=50)),
                ('nombre_presidente', models.CharField(max_length=60)),
                ('direccion_parroquia', models.CharField(max_length=60)),
                ('telefono_parroquia', models.CharField(max_length=10)),
                ('correo_parroquia', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Parroquia',
                'verbose_name_plural': 'Parroquias',
                'db_table': 'parroquia',
                'ordering': ['nombre_parroquia'],
            },
        ),
        migrations.CreateModel(
            name='Agrupacion',
            fields=[
                ('id_agrupacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_agrupacion', models.CharField(max_length=60)),
                ('nombre_contacto', models.CharField(max_length=60)),
                ('telefono_contacto', models.CharField(max_length=10)),
                ('direccion_agrupacion', models.CharField(blank=True, max_length=200, null=True)),
                ('ruc', models.CharField(blank=True, max_length=13, null=True)),
                ('correo_agrupacion', models.CharField(blank=True, max_length=50, null=True)),
                ('observacion', models.CharField(max_length=200, null=True)),
                ('tipo', models.CharField(max_length=1)),
                ('id_ambito', models.ForeignKey(blank=True, db_column='id_ambito', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ambito', to='ACulturales.ambitocultural')),
                ('id_categoria', models.ForeignKey(blank=True, db_column='id_categoria', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='categoria', to='ACulturales.categoria')),
                ('id_parroquia', models.ForeignKey(blank=True, db_column='id_parroquia', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='parroquia', to='ACulturales.parroquia')),
            ],
            options={
                'verbose_name': 'Agrupacion',
                'verbose_name_plural': 'Agrupaciones',
                'db_table': 'agrupacion',
            },
        ),
    ]
