# Generated by Django 3.1 on 2020-09-01 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ACulturales', '0002_auto_20200831_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agrupacion',
            name='id_agrupacion',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
