# Generated by Django 3.1 on 2020-09-02 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ACulturales', '0006_auto_20200901_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agrupacion',
            name='correo_agrupacion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='correo'),
        ),
        migrations.AlterField(
            model_name='agrupacion',
            name='direccion_agrupacion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='direccion'),
        ),
        migrations.AlterField(
            model_name='agrupacion',
            name='nombre_agrupacion',
            field=models.CharField(max_length=60, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='agrupacion',
            name='nombre_contacto',
            field=models.CharField(max_length=60, verbose_name='nombre Contacto'),
        ),
        migrations.AlterField(
            model_name='agrupacion',
            name='observacion',
            field=models.CharField(max_length=200, null=True, verbose_name='observacion'),
        ),
        migrations.AlterField(
            model_name='agrupacion',
            name='ruc',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='ruc'),
        ),
        migrations.AlterField(
            model_name='agrupacion',
            name='telefono_contacto',
            field=models.CharField(max_length=10, verbose_name='telefono'),
        ),
        migrations.AlterField(
            model_name='agrupacion',
            name='tipo',
            field=models.CharField(max_length=1, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='ambitocultural',
            name='nombre_ambito',
            field=models.CharField(max_length=70, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre_categoria',
            field=models.CharField(max_length=50, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='parroquia',
            name='correo_parroquia',
            field=models.CharField(max_length=50, verbose_name='correo GAD'),
        ),
        migrations.AlterField(
            model_name='parroquia',
            name='direccion_parroquia',
            field=models.CharField(max_length=60, verbose_name='direccion GAD'),
        ),
        migrations.AlterField(
            model_name='parroquia',
            name='nombre_parroquia',
            field=models.CharField(max_length=50, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='parroquia',
            name='nombre_presidente',
            field=models.CharField(max_length=60, verbose_name='presidente'),
        ),
        migrations.AlterField(
            model_name='parroquia',
            name='telefono_parroquia',
            field=models.CharField(max_length=10, verbose_name='telefono GAD'),
        ),
    ]
