# Generated by Django 3.1 on 2020-09-03 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ACulturales', '0007_auto_20200901_2305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agrupacion',
            options={'ordering': ['nombre_agrupacion'], 'verbose_name': 'Agrupacion', 'verbose_name_plural': 'Agrupaciones'},
        ),
        migrations.AlterModelOptions(
            name='ambitocultural',
            options={'ordering': ['nombre_ambito'], 'verbose_name': 'Ambito Cultural', 'verbose_name_plural': 'Ambitos Culturales'},
        ),
    ]
